import './globals.css'
import Script from 'next/script'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Script src="js/theme.js" id="theme-script" strategy="beforeInteractive"></Script>
        {children}
      </body>
    </html>
  )
}
